stages:
  - build

docker_build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$(git describe --tags --abbrev=0) .
    - docker push $CI_REGISTRY_IMAGE