services:
  core:
    build: .
    container_name: lumi-core
    restart: always
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb
    container_name: lumi-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    volumes:
      - ./db/migrations:/docker-entrypoint-initdb.d/
      - database:/var/lib/mysql/
    healthcheck:
      test: [ "CMD", "mariadb", "-h", "localhost", "-u", "${MARIADB_USER}", "-p${MARIADB_PASSWORD}", "-e", "SELECT 1" ]
      interval: 5s
      timeout: 10s
      retries: 5

  adminer:
    image: adminer
    container_name: lumi-adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  database:
