services:
  core:
    build: .
    restart: always
    environment:
      LUMI_TOKEN: ${TOKEN}
      LUMI_INSTANCE: ${INSTANCE}
      LUMI_OWNER_ID: ${OWNER_ID}
      LUMI_XP_GAIN_PER_MESSAGE: ${XP_GAIN_PER_MESSAGE}
      LUMI_XP_GAIN_COOLDOWN: ${XP_GAIN_COOLDOWN}
      LUMI_DBX_OAUTH2_REFRESH_TOKEN: ${DBX_OAUTH2_REFRESH_TOKEN}
      LUMI_DBX_APP_KEY: ${DBX_APP_KEY}
      LUMI_DBX_APP_SECRET: ${DBX_APP_SECRET}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    volumes:
      - debuglog:/usr/src/app/logs
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d/
      - dbdata:/var/lib/mysql/
    healthcheck:
      test: [ "CMD", "mariadb", "-h", "localhost", "-u", "${MARIADB_USER}", "-p${MARIADB_PASSWORD}", "-e", "SELECT 1" ]
      interval: 5s
      timeout: 10s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  dbdata:
  debuglog:
