services:
  core:
    build: .
    container_name: lumi-core
    restart: always
    develop:
      watch:
        - action: sync
          path: .
          target: /usr/src/app/
          ignore:
            - .venv/
            - data/
    env_file:
      - path: ./.env
        required: true
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb
    container_name: lumi-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    volumes:
      - ./data:/var/lib/mysql/
    healthcheck:
      test: [ "CMD", "mariadb", "-h", "localhost", "-u", "${MARIADB_USER}", "-p${MARIADB_PASSWORD}", "-e", "SELECT 1" ]
      interval: 5s
      timeout: 10s
      retries: 5

  adminer:
    image: adminer
    container_name: lumi-adminer
    restart: always
    ports:
      - 8080:8080
    env_file:
      - path: .env
        required: true
    environment:
      ADMINER_DEFAULT_DRIVER: mysql
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DEFAULT_DB: ${MARIADB_DATABASE}
      ADMINER_DEFAULT_USERNAME: ${MARIADB_USER}
      ADMINER_DEFAULT_PASSWORD: ${MARIADB_PASSWORD}
      ADMINER_DESIGN: dracula
    command: ["sh", "-c", "php -S 0.0.0.0:8080 -t /var/www/html"]
    configs:
      - source: adminer-index.php
        target: /var/www/html/index.php
    depends_on:
      db:
        condition: service_healthy

configs:
  adminer-index.php:
    content: |
      <?php
        if(!count($$_GET)) {
          $$_POST['auth'] = [
            'server' => $$_ENV['ADMINER_DEFAULT_SERVER'],
            'username' => $$_ENV['ADMINER_DEFAULT_USERNAME'],
            'password' => $$_ENV['ADMINER_DEFAULT_PASSWORD'],
            'driver' => $$_ENV['ADMINER_DEFAULT_DRIVER'],
            'db'    => $$_ENV['ADMINER_DEFAULT_DB'],
          ];
        }
        include './adminer.php';
      ?>