version: '3.8'

services:
  core:
    build: .
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    environment:
      RACU_TOKEN: ${TOKEN}
      RACU_INSTANCE: ${INSTANCE}
      RACU_OWNER_IDS: ${OWNER_IDS}
      RACU_XP_GAIN_PER_MESSAGE: ${XP_GAIN_PER_MESSAGE}
      RACU_XP_GAIN_COOLDOWN: ${XP_GAIN_COOLDOWN}
      RACU_DBX_OAUTH2_REFRESH_TOKEN: ${DBX_OAUTH2_REFRESH_TOKEN}
      RACU_DBX_APP_KEY: ${DBX_APP_KEY}
      RACU_DBX_APP_SECRET: ${DBX_APP_SECRET}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    volumes:
      - debuglog:/usr/src/app/logs
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d/
      - dbdata:/var/lib/mysql/
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    healthcheck:
      test: [ "CMD", "mariadb", "-h", "localhost", "-u", "${MARIADB_USER}", "-p${MARIADB_PASSWORD}", "-e", "SELECT 1" ]
      interval: 5s
      timeout: 10s
      retries: 5

  adminer:
    image: adminer
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    ports:
      - 8080:8080

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    environment:
      DOZZLE_ADDR: :8081
      DOZZLE_BASE: /docker
      DOZZLE_AUTH_PROVIDER: simple
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/data
    ports:
      - 8081:8081

volumes:
  dbdata:
  debuglog:
