art:
  fetch_url: https://git.wlinator.org/Luminara/Art/raw/branch/main/
  logo:
    opaque: lumi_logo.png
    transparent: lumi_logo_transparent.png
  icons:
    boost: lumi_boost.png
    check: lumi_check.png
    cross: lumi_cross.png
    exclaim: lumi_exclaim.png
    info: lumi_info.png?_=2
    hammer: lumi_hammer.png
    money_bag: lumi_money_bag.png
    money_coins: lumi_money_coins.png
    question: lumi_question.png
    streak: lumi_streak.png
    streak_bronze: lumi_streak_bronze.png\
    streak_gold: lumi_streak_gold.png
    streak_silver: lumi_streak_silver.png
    warning: lumi_warning.png
  juicybblue:
    flowers: https://i.imgur.com/79XfsbS.png
    teapot: https://i.imgur.com/wFsgSnr.png
    muffin: https://i.imgur.com/hSauh7K.png
  other:
    cloud: https://i.imgur.com/rc68c43.png
    trophy: https://i.imgur.com/dvIIr2G.png

cogs:
  ignore: # add cogs to ignore here

colors:
  color_default: 0xFF8C00
  color_warning: 0xFF7600
  color_error: 0xFF4500

economy:
  daily_reward: 500
  blackjack_multiplier: 1.4
  blackjack_hit_emoji: <:hit:1119262723285467156>
  blackjack_stand_emoji: <:stand:1118923298298929154>
  slots_multipliers:
    pair: 1.5
    three_of_a_kind: 4
    three_diamonds: 6
    jackpot: 15

emotes:
  guild_id: 1038051105642401812
  emote_ids:
    slots_animated_id: 1119262805309259776
    slots_0_id: 1119262803816095825
    slots_1_id: 1119262801261760592
    slots_2_id: 1119262800049614939
    slots_3_id: 1119262796497039510
    slots_4_id: 1119262794676715681
    slots_5_id: 1119262792386621555
    slots_6_id: 1119262791061229669
    S_Wide: 1119286730302955651
    L_Wide: 1119286763802857533
    O_Wide: 1119286787169329203
    T_Wide: 1119286804634406942
    CBorderBLeft: 1119286973572595712
    CBorderBRight: 1119286918459445408
    CBorderTLeft: 1119287006464331806
    CBorderTRight: 1119286865284051035
    HBorderB: 1119286936155213835
    HBorderT: 1119287027662344322
    VBorder: 1119286889854279680
    WSmall: 1119288536282173490
    ISmall: 1119288552673517608
    NSmall: 1119288579382857830
    LCentered: 1119287296127156325
    OCentered: 1119287563245584394
    SCentered: 1119287327588634647
    ECentered: 1119287343833165945
    Blank: 1119287267001905283
    lost: 1119288454212243607

images:
  allowed_image_extensions:
    - .jpg
    - .png
    - .jpeg
  birthday_gif_url: https://media1.tenor.com/m/NXvU9jbBUGMAAAAC/fireworks.gif

info:
  title: Luminara
  author: wlinator
  repository_url: https://git.wlinator.org/Luminara/Lumi
  invite_url: https://discord.com/oauth2/authorize?client_id=1038050427272429588&permissions=8&scope=bot

introductions:
  intro_guild_id: 719227135151046699
  intro_channel_id: 973619250507972618
  intro_question_mapping:
    Nickname: how would you like to be identified in the server? (nickname)
    Age: how old are you?
    Region: where do you live?
    Languages: which languages do you speak?
    Pronouns: what are your preferred pronouns?
    Sexuality: what's your sexuality?
    Relationship status: what's your current relationship status?
    Likes & interests: likes & interests
    Dislikes: dislikes
    EXTRAS: "EXTRAS: job status, zodiac sign, hobbies, etc. Tell us about yourself!"

llm_config:
  api_url: "https://api.openai.com/v1"
  model: "gpt-4o"
  max_tokens: 4096
  temperature: 1.0
  system_prompt: "Your responses adhere to Discord's Terms of Service, are SFW and helpful. You are responding to a request from a server that revolves around Linux."

logs:
  level: DEBUG
  format: "<green>{time:YYYY-MM-DD HH:mm:ss}</green> | <level>{level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>"

xp:
  excluded_channel_ids:
    -
